name: build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "25 22 * * 1"

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CARGO_INCREMENTAL: 0
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: 1
      RUSTFLAGS: -D warnings
      RUSTDOCFLAGS: -D warnings

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Build docs
        run: cargo doc --verbose
      - name: Check formatting
        run: cargo fmt --check --verbose
      - name: Check clippy
        run: cargo clippy --all-targets --verbose
